Fix image
stemangiola/tidybulk pull request #251
Opened 2022-07-22 20:58 UTC by mblue9

2022-07-22 21:53 UTC, mblue9 commented
Getting this error in the actions
```
Quitting from lines 154-155 (introduction.Rmd) 
Error: processing vignette 'introduction.Rmd' failed with diagnostics:
tidybulk says: using SummarizedExperiment with aggregate_duplicates, you need to specify .transcript parameter. It should be a feature-wise column (e.g. gene symbol) that you want to collapse he features with (e.g. ensembl). It cannot be the representation of rownames(SummarizedExperiment), as those are unique by definition, and not part of rowData per-se.
```

2022-07-25 16:25 UTC, stemangiola commented
@mblue9 hello

2022-07-25 16:27 UTC, stemangiola requested changes

2022-07-25 16:27 UTC, stemangiola commented on vignettes/introduction.Rmd
> +counts_SE.aggr = counts_SE %>% aggregate_duplicates()
@mblue9

2022-07-25 20:40 UTC, mblue9 commented
Superceded by https://github.com/stemangiola/tidybulk/pull/254

2022-07-25 20:40 UTC, closed without merging